## YAML Template.
- name: Installation d'apache
  hosts: all
  tasks: 
    - name: Inscrire le nouveau dépot
      apt_repository:
        repo: deb http://ftp.fr.debian.org/debian/ stretch main
        state: present
        update_cache: yes
    - name: Installation d'apache2
      apt:
        name: apache2,ca-certificates,apt-transport-https
        state: present
    - name: Démarrer le service Apache
      service:
        name: apache2
        state: started
        enabled: yes
    - name: Enregistrer une clé
      apt_key:
        url: https://packages.sury.org/php/apt.gpg
        state: present
    - name: Inscrire le nouveau dépot
      apt_repository:
        repo: deb https://packages.sury.org/php/ stretch main
        state: present
        update_cache: yes
    - name: Installation de PHP7.2
      apt:
        name: php7.2
        state: present
- name: Installation de MySql
  hosts: all
  tasks:
    - name: Inscrire le nouveau dépot
      apt_repository:
        repo: deb http://ftp.fr.debian.org/debian/ stretch main
        state: present
        update_cache: yes
    - name: Installation python-pip et python-mysqldb
      apt:
        name: python-pip,python-mysqldb
        state: present
    - name: Installation du module python pour MySQL
      pip:
        name: PyMySQL
    - name: Installation de mysql-server
      apt:
        name: mysql-server
        state: present
    - name: Gestion du .my.cnf
      copy:
        src: /root/autres/my.cnf.j2
        dest: /root/.my.cnf
        owner: root
        group: root
        mode: 0600
    - name: Redemarrage de mysql
      service:
        name: mysql
        state: restarted
        enabled: yes
    - name: Gestion du mot de passe du root
      mysql_user:
        name: root
        password: btsinfo
        login_unix_socket: /var/run/mysqld/mysqld.sock
        
        
        
        